spring.application.name=PennyMonte

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/pennydb
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.show-sql=true

# Disable Hibernate auto table creation
spring.jpa.hibernate.ddl-auto=none

# Ensure Liquibase (and other DataSource initializers) run before JPA uses the DataSource
spring.jpa.defer-datasource-initialization=true

# Liquibase
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml